//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sub1 {
    
    
    public class Queue5HandlerProxy : global::Bridge.Abstraction.IHandlerProxy {
        
        private global::Bridge.IPublisher _publisher;
        
        private global::Bridge.MQType _mqType;
        
        public Queue5HandlerProxy(global::Bridge.IPublisher publisher) {
            _publisher = publisher;
            _mqType = global::Bridge.MQType.ActiveMQ;
        }
        
        public async Task<System.Collections.Generic.IEnumerable<Bridge.Message.MsgTmp>> Action1Async(Bridge.Message.MsgTmp msg) {
            return await _publisher.PublishAndWaitReplyAsync<Bridge.Message.MsgTmp, System.Collections.Generic.IEnumerable<Bridge.Message.MsgTmp>>(_mqType, "queue5", "Action1", msg);
        }
    }
}
