//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proxy.Model {
    
    
    public class ProxyModel {
    }
}
namespace Bridge.Message {
    
    
    public class MsgTmp1 {
        
        private B.M.MsgTmp2 _msgTmp2;
        
        public B.M.MsgTmp2 MsgTmp2 {
            get {
                return this._msgTmp2;
            }
            set {
                this._msgTmp2 = value;
            }
        }
    }
    
    public class MsgTmp {
        
        private string _name;
        
        private int _age;
        
        private Bridge.Message.MsgTmp1 _msgTmp1;
        
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        public int Age {
            get {
                return this._age;
            }
            set {
                this._age = value;
            }
        }
        
        public Bridge.Message.MsgTmp1 MsgTmp1 {
            get {
                return this._msgTmp1;
            }
            set {
                this._msgTmp1 = value;
            }
        }
    }
}
namespace B.M {
    
    
    public class MsgTmp2 {
        
        private int _age;
        
        public int Age {
            get {
                return this._age;
            }
            set {
                this._age = value;
            }
        }
    }
}
