//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proxy {
    
    
    public class Queue3HandlerProxy {
        
        private Bridge.IPublisher _publisher;
        
        private Bridge.MQType _mqType;
        
        public Queue3HandlerProxy(Bridge.IPublisher publisher) {
            _publisher = publisher;
            _mqType = Bridge.MQType.ActiveMQ;
        }
        
        public async Task Test1(Bridge.Message.MsgTmp msg) {
            await _publisher.PublishMulticastAsync(_mqType, "queue3", "Test1", msg);
        }
    }
}
