//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proxy {
    
    
    public class Queue4HandlerProxy {
        
        private Bridge.IPublisher _publisher;
        
        private Bridge.MQType _mqType;
        
        public Queue4HandlerProxy(Bridge.IPublisher publisher) {
            _publisher = publisher;
            _mqType = Bridge.MQType.ActiveMQ;
        }
        
        public async Task Test1Async(Bridge.Message.MsgTmp msg) {
            await _publisher.PublishMulticastAsync(_mqType, "queue4", "Test1", msg);
        }
        
        public async Task Test2Async(Bridge.Message.MsgTmp msg) {
            await _publisher.PublishMulticastAsync(_mqType, "queue4", "Test2", msg);
        }
        
        public async Task Test3Async(System.Collections.Generic.IEnumerable<Bridge.Message.MsgTmp> msgs) {
            await _publisher.PublishMulticastAsync(_mqType, "queue4", "Test3", msgs);
        }
        
        public async Task Test4Async(int i) {
            await _publisher.PublishMulticastAsync(_mqType, "queue4", "Test4", i);
        }
    }
}
