//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sub2.Bridge.Message {
    
    
    public class MsgTmp {
        
        private Bridge.Message.strct _strct;
        
        private string _name;
        
        private int _age;
        
        private Bridge.Message.MsgTmp1 _msgTmp1;
        
        public Bridge.Message.strct strctf;
        
        public Bridge.Message.strct strct {
            get {
                return this._strct;
            }
            set {
                this._strct = value;
            }
        }
        
        public string Name {
            get {
                return this._name;
            }
            set {
                this._name = value;
            }
        }
        
        public int Age {
            get {
                return this._age;
            }
            set {
                this._age = value;
            }
        }
        
        public Bridge.Message.MsgTmp1 MsgTmp1 {
            get {
                return this._msgTmp1;
            }
            set {
                this._msgTmp1 = value;
            }
        }
    }
    
    public struct strct {
        
        public int id;
        
        public string name;
        
        public string description;
    }
    
    public class MsgTmp1 {
        
        private B.M.MsgTmp2 _msgTmp2;
        
        private TEST<int, int> _t1;
        
        private TEST<LSS.VehicleIntegrationTransaction.Model.Enums.InventoryStatus, int> _t2;
        
        public B.M.MsgTmp2 MsgTmp2 {
            get {
                return this._msgTmp2;
            }
            set {
                this._msgTmp2 = value;
            }
        }
        
        public TEST<int, int> T1 {
            get {
                return this._t1;
            }
            set {
                this._t1 = value;
            }
        }
        
        public TEST<LSS.VehicleIntegrationTransaction.Model.Enums.InventoryStatus, int> T2 {
            get {
                return this._t2;
            }
            set {
                this._t2 = value;
            }
        }
    }
}
namespace Sub2.B.M {
    
    
    public class MsgTmp2 {
        
        private int _age;
        
        public int Age {
            get {
                return this._age;
            }
            set {
                this._age = value;
            }
        }
    }
}
namespace Sub2 {
    
    
    public class TEST<T1, T2> {
        
        private T1 _t;
        
        private T2 _t2;
        
        public T1 t {
            get {
                return this._t;
            }
            set {
                this._t = value;
            }
        }
        
        public T2 t2 {
            get {
                return this._t2;
            }
            set {
                this._t2 = value;
            }
        }
    }
}
namespace Sub2.LSS.VehicleIntegrationTransaction.Model.Enums {
    
    
    public enum InventoryStatus {
        
        Allocated = 3,
        
        Available = 4,
        
        Invoiced = 8,
        
        Delivered = 9,
        
        Retailed = 10,
    }
}
